# Generated by Django 2.1 on 2018-08-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('username', models.CharField(max_length=8, unique=True, verbose_name='用户名')),
                ('phone', models.IntegerField(verbose_name='联系手机号')),
                ('email', models.EmailField(max_length=11, verbose_name='邮箱')),
                ('role', models.IntegerField(verbose_name='用户角色')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息表',
                'db_table': 'userInfo',
            },
        ),
    ]
