# Generated by Django 2.1 on 2018-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceTestManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('projectName', models.CharField(max_length=10, verbose_name='项目名称')),
                ('projectdesc', models.TextField(verbose_name='项目说明')),
                ('username', models.CharField(max_length=10, unique=False, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '项目表',
                'db_table': 'project',
            },
        ),
    ]
