# Generated by Django 2.1 on 2018-10-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('InterfaceTestManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_id',
            field=models.CharField(max_length=30, null=True, verbose_name='用例id'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='resp_data',
            field=models.CharField(max_length=50, null=True, verbose_name='提前依赖的json数据'),
        ),
    ]
